In [1]:
class Employee:
    # Class variable to count the number of employees
    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    # Method to calculate average salary
    @staticmethod
    def average_salary(employees):
        total_salary = sum(employee.salary for employee in employees)
        return total_salary / len(employees)

# FulltimeEmployee class inherits from Employee class
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

# Create instances of FulltimeEmployee and Employee classes
emp1 = Employee("hamsika", "Pranay", 50000, "HR")
emp2 = FulltimeEmployee("Dolly", "Sunny", 60000, "Engineering")
emp3 = FulltimeEmployee("Charlie", "Williams", 70000, "Marketing")

# List of all employees
employees = [emp1, emp2, emp3]

# Calculate and print the average salary
average_salary = Employee.average_salary(employees)
print(f"Average Salary: ${average_salary:.2f}")

# Print the number of employees
print(f"Total number of employees: {Employee.employee_count}")


Average Salary: $60000.00
Total number of employees: 3


In [2]:
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

# Reshape the array to 4 by 5
reshaped_array = random_vector.reshape(4, 5)

# Replace the max in each row by 0
reshaped_array[np.arange(reshaped_array.shape[0]), reshaped_array.argmax(axis=1)] = 0

print("Original Random Vector:")
print(random_vector)
print("\nReshaped Array (4x5):")
print(reshaped_array)


Original Random Vector:
[18.01464573  7.27207011  0.          3.91169638 18.98063191  1.79459894
 14.40913334 14.37191959  0.         11.27522421  1.64261997  8.62727227
 18.0026133  11.16839318  0.         14.65473766  0.         16.44570863
  6.22683825  5.55937238]

Reshaped Array (4x5):
[[18.01464573  7.27207011  0.          3.91169638 18.98063191]
 [ 1.79459894 14.40913334 14.37191959  0.         11.27522421]
 [ 1.64261997  8.62727227 18.0026133  11.16839318  0.        ]
 [14.65473766  0.         16.44570863  6.22683825  5.55937238]]


video link:https://drive.google.com/file/d/1RmYkLHNgt964BuboXsACUcybryizWesY/view?usp=drive_link